import { Topic } from "../context/TopicsContext";

export const demoTopics: Omit<Topic, "id">[] = [
  {
    name: "Variables and Data Types",
    description: "Understanding basic data structures like numbers, strings, and booleans",
    category: "Computer Science",
    difficulty: "beginner",
    status: "not-started",
  },
  {
    name: "Control Flow",
    description: "If statements, loops, and conditional logic",
    category: "Computer Science",
    difficulty: "beginner",
    status: "not-started",
  },
  {
    name: "Functions and Methods",
    description: "Creating reusable code blocks and understanding scope",
    category: "Computer Science",
    difficulty: "beginner",
    status: "not-started",
  },
  {
    name: "Object-Oriented Programming",
    description: "Classes, inheritance, and encapsulation",
    category: "Computer Science",
    difficulty: "intermediate",
    status: "not-started",
  },
  {
    name: "Data Structures",
    description: "Arrays, linked lists, stacks, queues, and trees",
    category: "Computer Science",
    difficulty: "intermediate",
    status: "not-started",
  },
  {
    name: "Algorithms",
    description: "Sorting, searching, and algorithm complexity",
    category: "Computer Science",
    difficulty: "intermediate",
    status: "not-started",
  },
  {
    name: "Database Fundamentals",
    description: "SQL, NoSQL, and data modeling",
    category: "Computer Science",
    difficulty: "intermediate",
    status: "not-started",
  },
  {
    name: "Web Development Basics",
    description: "HTML, CSS, and JavaScript fundamentals",
    category: "Computer Science",
    difficulty: "beginner",
    status: "not-started",
  },
  {
    name: "React Framework",
    description: "Component-based UI development with React",
    category: "Computer Science",
    difficulty: "advanced",
    status: "not-started",
  },
  {
    name: "API Design",
    description: "RESTful APIs and GraphQL",
    category: "Computer Science",
    difficulty: "advanced",
    status: "not-started",
  },
  {
    name: "Linear Algebra",
    description: "Vectors, matrices, and linear transformations",
    category: "Mathematics",
    difficulty: "intermediate",
    status: "not-started",
  },
  {
    name: "Calculus I",
    description: "Limits, derivatives, and integration",
    category: "Mathematics",
    difficulty: "intermediate",
    status: "not-started",
  },
  {
    name: "Statistics",
    description: "Probability, distributions, and hypothesis testing",
    category: "Mathematics",
    difficulty: "intermediate",
    status: "not-started",
  },
  {
    name: "Machine Learning Basics",
    description: "Supervised and unsupervised learning fundamentals",
    category: "Computer Science",
    difficulty: "advanced",
    status: "not-started",
  },
];
